=== gccornejo441/HUD_SDK_ARM/src/main/resources/gov/hud/arm/databag/agency_profile_databag_5_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://gov.hud.arm/agency_profile_databag_5_0" targetNamespace="http://gov.hud.arm/agency_profile_databag_5_0" xmlns:tns="http://gov.hud.arm/agency_profile_databag_5_0"
	xmlns:st="http://gov.hud.arm/arm_databag" elementFormDefault="qualified">
	<xs:import schemaLocation="simpleTypes5.0.xsd" namespace="http://gov.hud.arm/arm_databag" />
	<xs:element name="SubmissionData">
		<xs:complexType>
			<xs:all>
				<xs:element name="AgencyProfileData" type="AgencyProfileData" minOccurs="1" maxOccurs="1" />
				<xs:element name="Agency_Contacts" type="Agency_Contacts" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="AgencyProfileData">
		<xs:all>
			<xs:element name="Agency_EIN" type="st:employeeId" minOccurs="0" />
			<xs:element name="Reported_Month" type="st:month" />
			<xs:element name="Agency_DUN_Nbr" type="st:dunnBradstreetId" minOccurs="0" />
			<xs:element name="Agency_Physical_Address1" type="st:addressLineLong" />
			<xs:element name="Agency_Physical_Address2" type="st:addressLineLong" minOccurs="0" />
			<xs:element name="Agency_Physical_Address3" type="st:addressLineShort" minOccurs="0" />
			<xs:element name="Agency_Physical_Address4" type="st:addressLineShort" minOccurs="0" />
			<xs:element name="Agency_Physical_City" type="st:city" />
			<xs:element name="Agency_Physical_State" type="st:state" />
			<xs:element name="Agency_Physical_Zip" type="st:zip" />
			<xs:element name="Agency_Mailing_Address1" type="st:addressLineLong" minOccurs="0" />
			<xs:element name="Agency_Mailing_Address2" type="st:addressLineLong" minOccurs="0" />
			<xs:element name="Agency_Mailing_Address3" type="st:addressLineShort" minOccurs="0" />
			<xs:element name="Agency_Mailing_Address4" type="st:addressLineShort" minOccurs="0" />
			<xs:element name="Agency_Mailing_City" type="st:city" minOccurs="0" />
			<xs:element name="Agency_Mailing_State" type="st:state" minOccurs="0" />
			<xs:element name="Agency_Mailing_Zip" type="st:zip" minOccurs="0" />
			<xs:element name="Agency_Website" type="st:url" minOccurs="0" />
			<xs:element name="Agency_Phone_Nbr" type="st:phone" />
			<xs:element name="Agency_Tollfree_Phone_Nbr" type="st:phone" minOccurs="0" />
			<xs:element name="Agency_Fax_Nbr" type="st:phoneWithoutExtension" minOccurs="0" />
			<xs:element name="Agency_Email" type="st:email" minOccurs="0" />
			<xs:element name="Agency_Faith_Based_Ind" type="st:yesOrNo" />
			<xs:element name="Agency_Colonias_Ind" type="st:yesOrNo" />
			<xs:element name="Agency_Migrfarm_Worker_Ind" type="st:yesOrNo" />
			<xs:element name="Agency_Counseling_Budget_Amount" type="st:counselingBudgetAmount" />
			<xs:element name="Agency_Languages" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Language" type="st:languageId" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Agency_Counseling_Methods">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Counseling_Method" type="st:refId" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:all>
	</xs:complexType>
	<xs:complexType name="Agency_Contacts">
		<xs:sequence>
			<xs:element name="Agency_Contact" type="Agency_Contact" minOccurs="3" maxOccurs="3" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Agency_Contact">
		<xs:all>
			<xs:element name="Contact_Type" type="st:contactType" />
			<xs:element name="Contact_Fname" type="st:name" />
			<xs:element name="Contact_Lname" type="st:name" />
			<xs:element name="Contact_Mname" type="st:name" minOccurs="0" />
			<xs:element name="Contact_Title" type="st:shortRefId" />
			<xs:element name="Contact_Address1" type="st:addressLineLong" />
			<xs:element name="Contact_Address2" type="st:addressLineLong" minOccurs="0" />
			<xs:element name="Contact_City" type="st:city" />
			<xs:element name="Contact_State" type="st:state" />
			<xs:element name="Contact_Zip" type="st:zip" />
			<xs:element name="Contact_Phone_Nbr" type="st:phoneWithoutExtension" />
			<xs:element name="Contact_Ext_Nbr" type="st:phoneExtension" minOccurs="0" />
			<xs:element name="Contact_Mobile_Nbr" type="st:phoneWithoutExtension" minOccurs="0" />
			<xs:element name="Contact_Fax_Nbr" type="st:phoneWithoutExtension" minOccurs="0" />
			<xs:element name="Contact_Email" type="st:email" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== gccornejo441/HUD_SDK_ARM/src/main/resources/gov/hud/arm/databag/testAgencyProfileData.xml
<?xml version='1.0' encoding='UTF-8'?>
<tns:SubmissionData xsi:schemaLocation='http://gov.hud.arm/agency_profile_databag_5_0 agency_profile_databag_5_0.xsd' xmlns:tns='http://gov.hud.arm/agency_profile_databag_5_0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
	<tns:AgencyProfileData>
		<tns:Agency_EIN>38-6142925</tns:Agency_EIN>
		<tns:Reported_Month>6</tns:Reported_Month>
		<tns:Agency_DUN_Nbr>172773500</tns:Agency_DUN_Nbr>
		<tns:Agency_Physical_Address1>38505 Country Club Dr</tns:Agency_Physical_Address1>
		<tns:Agency_Physical_Address2>Suite 210</tns:Agency_Physical_Address2>
		<tns:Agency_Physical_City>Farmington Hills</tns:Agency_Physical_City>
		<tns:Agency_Physical_State>28</tns:Agency_Physical_State>
		<tns:Agency_Physical_Zip>48331</tns:Agency_Physical_Zip>
		<tns:Agency_Website>http://www.greenpath.com</tns:Agency_Website>
		<tns:Agency_Phone_Nbr>248-553-5400</tns:Agency_Phone_Nbr>
		<tns:Agency_Tollfree_Phone_Nbr>888-860-4167</tns:Agency_Tollfree_Phone_Nbr>
		<tns:Agency_Fax_Nbr>248-553-8970</tns:Agency_Fax_Nbr>
		<tns:Agency_Email>N/A</tns:Agency_Email>
		<tns:Agency_Faith_Based_Ind>N</tns:Agency_Faith_Based_Ind>
		<tns:Agency_Colonias_Ind>N</tns:Agency_Colonias_Ind>
		<tns:Agency_Migrfarm_Worker_Ind>N</tns:Agency_Migrfarm_Worker_Ind>
		<tns:Agency_Counseling_Budget_Amount>0.00</tns:Agency_Counseling_Budget_Amount>
		<tns:Agency_Counseling_Methods>
			<tns:Counseling_Method>1</tns:Counseling_Method>
			<tns:Counseling_Method>2</tns:Counseling_Method>
		</tns:Agency_Counseling_Methods>
		<tns:Agency_Languages>
			<tns:Language>19</tns:Language>
			<tns:Language>20</tns:Language>
		</tns:Agency_Languages>
	</tns:AgencyProfileData>
	<tns:Agency_Contacts>
		<tns:Agency_Contact>
			<tns:Contact_Type>11</tns:Contact_Type>
			<tns:Contact_Fname>Setina</tns:Contact_Fname>
			<tns:Contact_Lname>Briggs</tns:Contact_Lname>
			<tns:Contact_Title>1</tns:Contact_Title>
			<tns:Contact_Address1>38505 Country Club Dr</tns:Contact_Address1>
			<tns:Contact_Address2>Suite 210</tns:Contact_Address2>
			<tns:Contact_City>Farmington Hills</tns:Contact_City>
			<tns:Contact_State>28</tns:Contact_State>
			<tns:Contact_Zip>48331</tns:Contact_Zip>
			<tns:Contact_Phone_Nbr>248-553-5400</tns:Contact_Phone_Nbr>
			<tns:Contact_Ext_Nbr>2463</tns:Contact_Ext_Nbr>
			<tns:Contact_Fax_Nbr>248-553-8970</tns:Contact_Fax_Nbr>
			<tns:Contact_Email>sbriggs@greenpath.com</tns:Contact_Email>
		</tns:Agency_Contact>
		<tns:Agency_Contact>
			<tns:Contact_Type>2</tns:Contact_Type>
			<tns:Contact_Fname>Setina</tns:Contact_Fname>
			<tns:Contact_Lname>Briggs</tns:Contact_Lname>
			<tns:Contact_Title>1</tns:Contact_Title>
			<tns:Contact_Address1>38505 Country Club Dr</tns:Contact_Address1>
			<tns:Contact_Address2>Suite 210</tns:Contact_Address2>
			<tns:Contact_City>Farmington Hills</tns:Contact_City>
			<tns:Contact_State>28</tns:Contact_State>
			<tns:Contact_Zip>48331</tns:Contact_Zip>
			<tns:Contact_Phone_Nbr>248-553-5400</tns:Contact_Phone_Nbr>
			<tns:Contact_Ext_Nbr>2463</tns:Contact_Ext_Nbr>
			<tns:Contact_Fax_Nbr>248-553-8970</tns:Contact_Fax_Nbr>
			<tns:Contact_Email>sbriggs@greenpath.com</tns:Contact_Email>
		</tns:Agency_Contact>
		<tns:Agency_Contact>
			<tns:Contact_Type>3</tns:Contact_Type>
			<tns:Contact_Fname>Setina</tns:Contact_Fname>
			<tns:Contact_Lname>Briggs</tns:Contact_Lname>
			<tns:Contact_Title>1</tns:Contact_Title>
			<tns:Contact_Address1>38505 Country Club Dr</tns:Contact_Address1>
			<tns:Contact_Address2>Suite 210</tns:Contact_Address2>
			<tns:Contact_City>Farmington Hills</tns:Contact_City>
			<tns:Contact_State>28</tns:Contact_State>
			<tns:Contact_Zip>48331</tns:Contact_Zip>
			<tns:Contact_Phone_Nbr>248-553-5400</tns:Contact_Phone_Nbr>
			<tns:Contact_Ext_Nbr>2463</tns:Contact_Ext_Nbr>
			<tns:Contact_Fax_Nbr>248-553-8970</tns:Contact_Fax_Nbr>
			<tns:Contact_Email>sbriggs@greenpath.com</tns:Contact_Email>
		</tns:Agency_Contact>
	</tns:Agency_Contacts>
</tns:SubmissionData>
