=== gccornejo441/HUD_SDK_ARM/src/main/resources/gov/hud/arm/databag/counselor_profile_databag_5_0.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="http://gov.hud.arm/counselor_profile_databag_5_0" targetNamespace="http://gov.hud.arm/counselor_profile_databag_5_0"
	xmlns:st="http://gov.hud.arm/arm_databag" elementFormDefault="qualified">
	<xs:import schemaLocation="simpleTypes5.0.xsd" namespace="http://gov.hud.arm/arm_databag" />
	<xs:element name="SubmissionData">
		<xs:complexType>
			<xs:all>
				<xs:element name="Counselor_Profiles" type="Counselor_Profiles" minOccurs="0" />
				<xs:element name="Counselor_Training_Courses" type="Counselor_Training_Courses" minOccurs="0" />
				<xs:element name="Counselor_Trainings" type="Counselor_Trainings" minOccurs="0" />
			</xs:all>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="Counselor_Profiles">
		<xs:sequence>
			<xs:element name="Counselor_Profile" type="Counselor_Profile" minOccurs="1" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Counselor_Profile">
		<xs:all>
			<xs:element name="CMS_Counselor_Id" type="st:refId" />
			<xs:element name="Counselor_Fname" type="st:name" />
			<xs:element name="Counselor_Lname" type="st:name" />
			<xs:element name="Counselor_Mname" type="st:name" minOccurs="0" />
			<xs:element name="Counselor_Emp_Start_Date" type="st:date" />
			<xs:element name="Counselor_Emp_End_Date" type="st:date" minOccurs="0" />
			<xs:element name="Counselor_Rate" type="st:moneyField" minOccurs="0" />
			<xs:element name="Counselor_Billing_Method" type="st:billingMethods" minOccurs="0" />
			<xs:element name="Counselor_HUD_Id" type="st:fieldValue" minOccurs="0" />
			<xs:element name="Counselor_SSN" type="st:ssn"/>
			<xs:element name="Counselor_Phone" type="st:phone" minOccurs="0" />
			<xs:element name="Counselor_Email" type="st:email" minOccurs="0" />
			<xs:element name="Counselor_Languages" minOccurs="0" >
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Language" type="st:languageId" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>		
			<xs:element name="Counselor_Service_Types" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Service_Type" type="st:refId" maxOccurs="unbounded" />
					</xs:sequence>
				</xs:complexType>
			</xs:element>		
	</xs:all>
	</xs:complexType>
	<xs:complexType name="Counselor_Trainings">
		<xs:sequence>
			<xs:element name="Counselor_Training" type="Counselor_Training" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Counselor_Training">
		<xs:all>
			<xs:element name="CMS_Counselor_Id" type="st:refId" />
			<xs:element name="Counselor_Training_Cert" type="st:yesOrNo" />
			<xs:element name="Counselor_Training_Course_Id" type="st:refId" />
		</xs:all>
	</xs:complexType>
	<xs:complexType name="Counselor_Training_Courses">
		<xs:sequence>
			<xs:element name="Counselor_Training_Course" type="Counselor_Training_Course" maxOccurs="unbounded" />
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Counselor_Training_Course">
		<xs:all>
			<xs:element name="Counselor_Training_Course_Id" type="st:refId" />
			<xs:element name="Counselor_Training_Title" type="st:trainingTitle" />
			<xs:element name="Counselor_Training_Date" type="st:date" />
			<xs:element name="Counselor_Training_Org" type="st:otherTrainingOrganization" />
			<xs:element name="Counselor_Training_Org_Other" type="st:fieldValue" minOccurs="0" />
			<xs:element name="Counselor_Training_Sponsor" type="st:sponsorTrainingOrganization" />
			<xs:element name="Counselor_Training_Sponsor_Other" type="st:fieldValue" minOccurs="0" />
			<xs:element name="Counselor_Training_Duration" type="st:sessionDuration" minOccurs="0" />
		</xs:all>
	</xs:complexType>
</xs:schema>

=== gccornejo441/HUD_SDK_ARM/src/main/resources/gov/hud/arm/databag/testBadCounselorProfileData.xml
<?xml version="1.0" encoding="UTF-8"?>
<tns:SubmissionData xsi:schemaLocation='http://gov.hud.arm/counselor_profile_databag_5_0 counselor_profile_databag_5_0.xsd' xmlns:tns='http://gov.hud.arm/counselor_profile_databag_5_0' xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'>
  <tns:Counselor_Profiles>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>002</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Unassigned</tns:Counselor_Fname>
      <tns:Counselor_Lname>Cases</tns:Counselor_Lname>
      <tns:Counselor_Mname>C</tns:Counselor_Mname>
      <tns:Counselor_Emp_Start_Date>07-12-2000</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Hourly</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>reallyLongEmailAddress@nowhereinparticular.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>3</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_Service_Types>
	    <tns:Service_Type>3</tns:Service_Type>
	    <tns:Service_Type>12</tns:Service_Type>
	    <tns:Service_Type>7</tns:Service_Type>
	  </tns:Counselor_Service_Types>
	  <tns:Counselor_SSN>123-45-6789</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>206</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Yvonne</tns:Counselor_Fname>
      <tns:Counselor_Lname>Castillo</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>07-12-1998</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>175.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_SSN>111-22-3333</tns:Counselor_SSN>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>213</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Maria</tns:Counselor_Fname>
      <tns:Counselor_Lname>Enomoto</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>07-14-2000</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>menomoto@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>26</tns:Language>
	  	<tns:Language>19</tns:Language>
	  	<tns:Language>7</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>123-45-6789</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>244</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Carlos</tns:Counselor_Fname>
      <tns:Counselor_Lname>Zavala</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-09-2004</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>50.75</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Hourly</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>3</tns:Language>
	  	<tns:Language>11</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>333-11-2222</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>256</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Sonie</tns:Counselor_Fname>
      <tns:Counselor_Lname>May</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-06-2001</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_SSN>234-56-7878</tns:Counselor_SSN>
 	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
   </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>264</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Vianey</tns:Counselor_Fname>
      <tns:Counselor_Lname>Arroyo</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>02-11-2009</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>30.50</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Hourly</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>13</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>111-11-1111</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>276</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Elba</tns:Counselor_Fname>
      <tns:Counselor_Lname>Serrano</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>01-14-2009</tns:Counselor_Emp_Start_Date>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>20</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>123-45-6789</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>279</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Cassandra</tns:Counselor_Fname>
      <tns:Counselor_Lname>Molina</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>07-08-2009</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>99.99</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Hourly</tns:Counselor_Billing_Method>
	  <tns:Counselor_SSN>123-45-1234</tns:Counselor_SSN>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>281</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Ever</tns:Counselor_Fname>
      <tns:Counselor_Lname>Schettiny</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>06-06-2002</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  	<tns:Language>11</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>999-99-9999</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>296</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Mary Lee</tns:Counselor_Fname>
      <tns:Counselor_Lname>Castillo</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-01-2005</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
   	  <tns:Counselor_HUD_Id>123456789</tns:Counselor_HUD_Id>
	  <tns:Counselor_SSN>777-77-7777</tns:Counselor_SSN>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>290</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Debbie</tns:Counselor_Fname>
      <tns:Counselor_Lname>Bernal</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-04-2003</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_SSN>444-55-6677</tns:Counselor_SSN>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>302</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Denise</tns:Counselor_Fname>
      <tns:Counselor_Lname>Allyn</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-11-2003</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_SSN>111-22-6777</tns:Counselor_SSN>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Languages>
	  	<tns:Language>2</tns:Language>
	  </tns:Counselor_Languages>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>305</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Terence</tns:Counselor_Fname>
      <tns:Counselor_Lname>Mok</tns:Counselor_Lname>
      <tns:Counselor_Emp_Start_Date>12-09-2004</tns:Counselor_Emp_Start_Date>
  	  <tns:Counselor_Rate>100.00</tns:Counselor_Rate>
	  <tns:Counselor_Billing_Method>Fixed</tns:Counselor_Billing_Method>
	  <tns:Counselor_Email>unassigned@nowhere.com</tns:Counselor_Email>
	  <tns:Counselor_Phone>703-555-1212</tns:Counselor_Phone>
	  <tns:Counselor_Languages>
	  	<tns:Language>6</tns:Language>
	  	<tns:Language>13</tns:Language>
	  	<tns:Language>20</tns:Language>
	  </tns:Counselor_Languages>
	  <tns:Counselor_SSN>222-33-4455</tns:Counselor_SSN>
    </tns:Counselor_Profile>
    <tns:Counselor_Profile>
      <tns:CMS_Counselor_Id>307</tns:CMS_Counselor_Id>
      <tns:Counselor_Fname>Gerardo</tns:Counselor_Fname>
      <tns:Counselor_Lname>Garin</tns:Counselor_Lname>
